# Generated by Django 4.1 on 2024-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('machine_code', models.CharField(max_length=200)),
                ('time_zone', models.CharField(max_length=200)),
                ('actual_time', models.FloatField()),
                ('modulus', models.IntegerField()),
                ('per_mins', models.FloatField()),
                ('output', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
