# Generated by Django 4.1 on 2024-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_printingmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formingmachine',
            name='time_zone',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='printingmachine',
            name='time_zone',
            field=models.FloatField(),
        ),
    ]
