# Generated by Django 4.1 on 2024-04-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_formingmachine_time_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingmachine',
            name='modulus',
            field=models.IntegerField(null=True),
        ),
    ]
