# Generated by Django 4.1 on 2024-04-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_printingmachine_modulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formingmachine',
            name='actual_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='formingmachine',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='formingmachine',
            name='machine_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formingmachine',
            name='modulus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='formingmachine',
            name='output',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='formingmachine',
            name='per_mins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='formingmachine',
            name='time_zone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('error_amounts', models.IntegerField(null=True)),
                ('produce_time', models.FloatField(null=True)),
                ('employee', models.CharField(max_length=200, null=True)),
                ('form_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.formingmachine')),
            ],
        ),
    ]
