# Generated by Django 4.1 on 2024-04-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_delete_formingmachine_delete_printingmachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('machine_code', models.CharField(max_length=200)),
                ('time_zone', models.CharField(max_length=200)),
                ('actual_time', models.FloatField()),
                ('modulus', models.IntegerField(null=True)),
                ('per_mins', models.FloatField()),
                ('output', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('error_amounts', models.IntegerField(null=True)),
                ('produce_time', models.FloatField(null=True)),
                ('employee', models.CharField(max_length=200, null=True)),
                ('form_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.formingmachine')),
            ],
        ),
    ]
