# Generated by Django 4.1 on 2024-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='total_produce',
            field=models.IntegerField(null=True),
        ),
    ]
