# Generated by Django 4.1 on 2024-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_dailyreport_total_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='work_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
