# Generated by Django 4.1 on 2024-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_dailyreport_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='total_amounts_produce',
            field=models.FloatField(default=0),
        ),
    ]
