# Generated by Django 4.1 on 2024-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_dailyreport_total_amounts_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='error_amounts_percentage',
            field=models.FloatField(default=0),
        ),
    ]
