# Generated by Django 4.1 on 2024-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_dailyreport_work_time_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='turn_on_speed_per_mins',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
