# Generated by Django 4.1 on 2024-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_dailyreport_achieve_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='reasonable_produce',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='reasonable_produce_percentage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
